### ISSUE TITLE
references are not properly resolving

### ISSUE THREAD

**Issue by claytron5000** [mlambley/json-reference#1]
First, kudos for reviving this package.

Second, using the simple example docs I'm getting a reference object to the top of the json object, not the pointer.

With this json file:
```json
{
  "definitions": {
    "pet": {
      "type": "object",
      "properties": {
        "name":  { "type": "string" },
        "breed": { "type": "string" },
        "age":  { "type": "string" }
      },
      "required": ["name", "breed", "age"]
    }
  },
  "type": "object",
  "properties": {
    "cat": { "$ref": "#/definitions/pet" },
    "dog": { "$ref": "#/definitions/pet" }
  }
}
```
And this code:
```php
$pets = $dereferencer->dereference('file://' . dirname(__FILE__) .'/../../path/to/pets.json');
$cattype =$schema->properties->cat->type;
```
`$cattype` is null. And when I inspect the `$pets` object, `$schema->properties->cat` is a reference to an object with the properties `dereferencer, ref, scope, schema, resolved`. `schema` contains the actual cat schema, and `resolved` is null.

**Comment by mlambley** [comment]
Hey buddy, thank you for putting this together. I've been able to get this working using the following code.
```php
<?php
require_once 'vendor/autoload.php';

$dereferencer  = new League\JsonReference\Dereferencer();
$schema = $dereferencer->dereference('file:///C:/path/to/pets.json');
$cattype = $schema->properties->cat->type;
$required = $schema->properties->cat->required;

var_dump($cattype);
var_dump($required);
```
The output is as you might expect:
```
string(6) "object"
array(3) {
  [0]=>
  string(4) "name"
  [1]=>
  string(5) "breed"
  [2]=>
  string(3) "age"
}
```
I suspect you may simply have a typo in your code - perhaps you intended to store the dereferenced schema into `$schema`.

If you have any further questions please let me know, otherwise if you can confirm your fix is working please close this issue. Thank you.

**Comment by claytron5000** [comment]
That worked. I must have had a typo, thanks!
